### ISSUE TITLE
QA testing #1 

### ISSUE THREAD

**Issue by 158702209-myseneca** [168671188-myseneca/Group-Lab#2]
Issue Description - The game automatically exits after one round.
- We require to include a cycle so the user can continue playing if they like.

Developer Comments: - Add a loop design to prompt users to perform additional rounds.
- If the player decides to continue, resume the game loop. If not, leave the match alone.

**Comment by 168671188-myseneca** [comment]
Syntax error no longer present within code following iteration #1.

The program of the game either proceeds or ends based off the user's response.
